name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which version of the Three.js plugin are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: input
    id: construct-version
    attributes:
      label: Construct 3 Version
      description: Which version of Construct 3 are you using?
      placeholder: e.g., r350
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g., Windows 10, macOS 13, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. Set property...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any error messages from the browser console (F12 → Console tab)
      placeholder: Paste any error messages here
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or files that might help
      placeholder: You can drag and drop images here

  - type: checkboxes
    id: sample-project
    attributes:
      label: Sample Project
      options:
        - label: I can provide a minimal .c3p file that reproduces this issue
        - label: This happens in a new empty project
        - label: This happens only in my existing project
